import { Metadata } from "next";
import Link from "next/link";
import Breadcrumb from "@/components/Breadcrumb";
export const metadata: Metadata = { title: "Vem behöver ett UK ETA? Nationaliteter och undantag 2026", description: "Vem behöver ett UK ETA och vem är undantagen: brittiska och irländska medborgare, personer med uppehållstillstånd, airside-transit. Guide per nationalitet." };
export default function Page() {
  return (<div>
      <section className="sub-hero relative overflow-hidden">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src="/sub-hero/what-is-eta.jpg" alt="" className="absolute inset-0 w-full h-full object-cover" />
        <div className="absolute inset-0 sub-hero-scrim" />
        <div className="relative max-w-4xl mx-auto px-6 pt-12 pb-12 md:pt-14 md:pb-16">
          <p className="kicker mb-3 mt-4">UK ETA-INFORMATION</p>
          <h1 className="deco-head text-3xl md:text-4xl font-bold text-white mb-6" style={{ fontFamily: "var(--font-noto-serif), serif" }}><span className="deco-line" />Vem behöver ett UK ETA?</h1>
          <p className="text-white/90 leading-relaxed" dangerouslySetInnerHTML={{__html:`UK ETA krävs för medborgare i viseringsfria länder vid korta vistelser (turism, affärer, kort studietid). <strong>Varje resenär, inklusive spädbarn och barn, behöver ett eget ETA.</strong>`}} />
        </div></section>
      <section className="bg-gray-50"><div className="max-w-4xl mx-auto px-6 py-10"><h2 className="heading-band mb-6">Vem är undantagen från ETA</h2><ul className="space-y-3 text-gray-700 leading-relaxed"><li className="flex gap-2"><span className="text-[#022444] font-bold">•</span><span dangerouslySetInnerHTML={{__html:`Brittiska och irländska medborgare (med brittiskt/irländskt pass)`}} /></li><li className="flex gap-2"><span className="text-[#022444] font-bold">•</span><span dangerouslySetInnerHTML={{__html:`Personer med tillstånd att bo, arbeta eller studera i Storbritannien (t.ex. visum, settled/pre-settled status)`}} /></li><li className="flex gap-2"><span className="text-[#022444] font-bold">•</span><span dangerouslySetInnerHTML={{__html:`Innehavare av British Overseas Territories Citizen- eller British National (Overseas)-pass`}} /></li><li className="flex gap-2"><span className="text-[#022444] font-bold">•</span><span dangerouslySetInnerHTML={{__html:`Personer bosatta i Irland som reser från Irland, Guernsey, Jersey eller Isle of Man`}} /></li><li className="flex gap-2"><span className="text-[#022444] font-bold">•</span><span dangerouslySetInnerHTML={{__html:`Airside-transitresenärer som inte passerar gränskontrollen`}} /></li><li className="flex gap-2"><span className="text-[#022444] font-bold">•</span><span dangerouslySetInnerHTML={{__html:`Personer som väntar på beslut om en EU Settlement Scheme-ansökan`}} /></li></ul></div></section>
      <section className="bg-gray-50"><div className="max-w-4xl mx-auto px-6 py-10"><h2 className="heading-band mb-6">Viktigt att veta</h2><ul className="space-y-3 text-gray-700 leading-relaxed"><li className="flex gap-2"><span className="text-[#022444] font-bold">•</span><span dangerouslySetInnerHTML={{__html:`Personer med brittiskt eller irländskt medborgarskap kan inte få ETA och reser med det medborgarskapets dokument.`}} /></li><li className="flex gap-2"><span className="text-[#022444] font-bold">•</span><span dangerouslySetInnerHTML={{__html:`Om din nationalitet inte är viseringsfri kan du behöva visum: kontrollera med det officiella GOV.UK-verktyget.`}} /></li><li className="flex gap-2"><span className="text-[#022444] font-bold">•</span><span dangerouslySetInnerHTML={{__html:`Även spädbarn och barn behöver ett eget ETA.`}} /></li></ul></div></section>
      <section className="bg-white"><div className="max-w-4xl mx-auto px-6 py-8 text-sm text-gray-500"><p className="mb-2 font-bold text-gray-700">Officiella källor (GOV.UK)</p><ul className="space-y-1"><li><a href="https://www.gov.uk/eta/when-not-need-eta" target="_blank" rel="noopener noreferrer" className="text-[#022444] underline">https://www.gov.uk/eta/when-not-need-eta</a></li><li><a href="https://www.gov.uk/guidance/check-when-you-can-get-an-electronic-travel-authorisation-eta" target="_blank" rel="noopener noreferrer" className="text-[#022444] underline">https://www.gov.uk/guidance/check-when-you-can-get-an-electronic-travel-authorisation-eta</a></li></ul></div></section>
      <div className="max-w-4xl mx-auto px-6 py-8"><Breadcrumb items={[{ label: "Hem", href: "/" }, { label: "UK ETA-information", href: "/eta-info/what-is-eta" }, { label: "Vem behöver ett UK ETA?" }]} /></div>
    </div>);
}
