import { Metadata } from "next";
import Link from "next/link";
import Breadcrumb from "@/components/Breadcrumb";

export const metadata: Metadata = { title: "Standard Visitor-visum f\u00f6r UK: n\u00e4r ETA inte r\u00e4cker", description: "Om din UK ETA avsl\u00e5s (ingen \u00f6verklagan) eller om din nationalitet kr\u00e4ver visum, m\u00e5ste du ans\u00f6ka om ett Standard Visitor-visum f\u00f6r att resa till Storbritannien. " };

export default function Page() {
  const faqLd = "{\"@context\": \"https://schema.org\", \"@type\": \"FAQPage\", \"mainEntity\": [{\"@type\": \"Question\", \"name\": \"N\u00e4r beh\u00f6ver jag ett Standard Visitor-visum i st\u00e4llet f\u00f6r ETA?\", \"acceptedAnswer\": {\"@type\": \"Answer\", \"text\": \"N\u00e4r din nationalitet kr\u00e4ver visum f\u00f6r UK eller n\u00e4r ETA-ans\u00f6kan avslagits. ETA-avslag kan inte \u00f6verklagas \u2014 f\u00f6r att resa ans\u00f6ker du om r\u00e4tt visum.\"}}, {\"@type\": \"Question\", \"name\": \"Hur mycket kostar Standard Visitor-visumet?\", \"acceptedAnswer\": {\"@type\": \"Answer\", \"text\": \"Enligt GOV.UK kostar visum upp till 6 m\u00e5nader \u00a3135. L\u00e5ngtids: \u00a3506 (2 \u00e5r), \u00a3903 (5 \u00e5r), \u00a31 128 (10 \u00e5r). Transitvisum \u00a374,50.\"}}, {\"@type\": \"Question\", \"name\": \"Hur l\u00e5ng \u00e4r handl\u00e4ggningen?\", \"acceptedAnswer\": {\"@type\": \"Answer\", \"text\": \"Vanligtvis f\u00e5r du beslut inom 3 veckor efter bes\u00f6ket p\u00e5 visumcentret.\"}}, {\"@type\": \"Question\", \"name\": \"Hur l\u00e4nge f\u00e5r jag stanna i UK?\", \"acceptedAnswer\": {\"@type\": \"Answer\", \"text\": \"Standardvistelsen \u00e4r h\u00f6gst 6 m\u00e5nader per bes\u00f6k.\"}}]}";
  return (<div>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: faqLd }} />
      <section className="sub-hero relative overflow-hidden">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src="/sub-hero/official-gov-uk.jpg" alt="" className="absolute inset-0 w-full h-full object-cover" />
        <div className="absolute inset-0 sub-hero-scrim" />
        <div className="relative max-w-4xl mx-auto px-6 pt-12 pb-12 md:pt-14 md:pb-16">
          <p className="kicker mb-3 mt-4">INFORMATION OM UK ETA</p>
          <h1 className="deco-head text-3xl md:text-4xl font-bold text-white mb-6" style={{ fontFamily: "var(--font-noto-serif), serif" }}><span className="deco-line" />Standard Visitor-visum för UK: när ETA inte räcker</h1>
          <p className="text-white/90 leading-relaxed" dangerouslySetInnerHTML={{__html:`Om din <strong>UK ETA avslås</strong> (ingen överklagan) eller om din nationalitet <strong>kräver visum</strong>, måste du ansöka om ett <strong>Standard Visitor-visum</strong> för att resa till Storbritannien. Nedan fakta enligt GOV.UK.`}} />
        </div></section>
      <section className="bg-white"><div className="max-w-4xl mx-auto px-6 py-10"><h2 className="heading-band mb-6">Vem behöver visum i stället för ETA</h2><ul className="space-y-3 text-gray-700 leading-relaxed"><li className="flex gap-2"><span className="text-[#022444] font-bold">•</span><span>Personer vars nationalitet kräver visum för UK (inte berättigade till ETA).</span></li><li className="flex gap-2"><span className="text-[#022444] font-bold">•</span><span>Personer vars ETA-ansökan har <strong>avslagits</strong> — man kan inte resa in i UK med ETA, visum krävs.</span></li><li className="flex gap-2"><span className="text-[#022444] font-bold">•</span><span>Kontrollera vilket visum du behöver med verktyget ”check if you need a visa” på GOV.UK.</span></li></ul></div></section>
      <section className="bg-gray-50"><div className="max-w-4xl mx-auto px-6 py-10"><h2 className="heading-band mb-6">Avgifter (GOV.UK)</h2><div className="overflow-x-auto"><table className="w-full text-left text-gray-700 border-collapse"><tbody><tr className="border-b border-gray-200"><th className="py-3 pr-4 font-semibold">Standard Visitor (upp till 6 månader)</th><td className="py-3">£135</td></tr><tr className="border-b border-gray-200"><th className="py-3 pr-4 font-semibold">Långtids — 2 år</th><td className="py-3">£506</td></tr><tr className="border-b border-gray-200"><th className="py-3 pr-4 font-semibold">Långtids — 5 år</th><td className="py-3">£903</td></tr><tr className="border-b border-gray-200"><th className="py-3 pr-4 font-semibold">Långtids — 10 år</th><td className="py-3">£1 128</td></tr><tr><th className="py-3 pr-4 font-semibold">Transitvisum</th><td className="py-3">£74,50</td></tr></tbody></table></div><p className="mt-4 text-sm text-gray-500">Långtidsvisum tillåter flera inresor, men varje vistelse är begränsad till 6 månader. Belopp enligt GOV.UK — kan ändras.</p></div></section>
      <section className="bg-white"><div className="max-w-4xl mx-auto px-6 py-10"><h2 className="heading-band mb-6">Tid, giltighet och vistelse</h2><ul className="space-y-3 text-gray-700 leading-relaxed"><li className="flex gap-2"><span className="text-[#022444] font-bold">•</span><span><strong>Beslut:</strong> vanligtvis inom 3 veckor efter besöket på visumcentret.</span></li><li className="flex gap-2"><span className="text-[#022444] font-bold">•</span><span><strong>Vistelse:</strong> högst 6 månader per besök.</span></li><li className="flex gap-2"><span className="text-[#022444] font-bold">•</span><span><strong>När du ansöker:</strong> tidigast 3 månader före resan.</span></li></ul></div></section>
      <section className="bg-gray-50"><div className="max-w-4xl mx-auto px-6 py-10"><h2 className="heading-band mb-6">Så ansöker du (GOV.UK)</h2><ol className="space-y-3 text-gray-700 leading-relaxed list-decimal pl-5"><li>Ansök online (du kan spara och slutföra senare).</li><li>Boka tid på ett visumansökningscenter.</li><li>Kom till besöket för att styrka identitet och lämna <strong>biometri</strong> (fingeravtryck och foto) samt dokument.</li><li>Du får beslutet via e-post; passet återlämnas på centret.</li></ol><p className="mt-4 text-sm font-semibold text-gray-700">Förbered bland annat:</p><ul className="mt-2 space-y-2 text-sm text-gray-600"><li>• Giltigt pass (giltigt under hela vistelsen)</li><li>• Resedatum, boende och uppskattad kostnad</li><li>• Nuvarande adress och boendetid</li><li>• Årsinkomst (om tillämpligt) och arbetsgivaruppgifter (om tillämpligt)</li><li>• Eventuell brotts- / immigrationshistorik</li><li>• Bestyrkta översättningar av dokument som inte är på engelska eller walesiska</li></ul></div></section>
      <section className="bg-white"><div className="max-w-4xl mx-auto px-6 py-10"><h2 className="heading-band mb-6">Relaterad information</h2><div className="grid gap-3 md:grid-cols-3"><Link href="/eta-info/eta-avslag" className="block border border-gray-200 rounded-lg p-4 hover:border-[#022444] transition-colors"><p className="font-semibold text-[#022444]">Vad du gör efter ett ETA-avslag</p><p className="text-sm text-gray-500 mt-1">Avslag och alternativ</p></Link><Link href="/eta-info/eta-eller-visum" className="block border border-gray-200 rounded-lg p-4 hover:border-[#022444] transition-colors"><p className="font-semibold text-[#022444]">ETA eller visum?</p><p className="text-sm text-gray-500 mt-1">När ETA räcker</p></Link><Link href="/eta-info/vem-behover" className="block border border-gray-200 rounded-lg p-4 hover:border-[#022444] transition-colors"><p className="font-semibold text-[#022444]">Vem behöver ETA</p><p className="text-sm text-gray-500 mt-1">Behörighet</p></Link></div></div></section>
      <section className="bg-gray-50"><div className="max-w-4xl mx-auto px-6 py-8 text-sm text-gray-500"><p className="mb-2 font-bold text-gray-700">Officiella källor (GOV.UK)</p><ul className="space-y-1"><li><a href="https://www.gov.uk/standard-visitor" target="_blank" rel="noopener noreferrer" className="text-[#022444] underline">https://www.gov.uk/standard-visitor</a></li><li><a href="https://www.gov.uk/standard-visitor/apply-standard-visitor-visa" target="_blank" rel="noopener noreferrer" className="text-[#022444] underline">https://www.gov.uk/standard-visitor/apply-standard-visitor-visa</a></li></ul><p className="mt-3">Detta är en oberoende informationstjänst, inte en statlig webbplats. Uppgifter och avgifter kan ändras — kontrollera alltid officiella uppgifter på GOV.UK före ansökan.</p></div></section>
      <div className="max-w-4xl mx-auto px-6 py-8"><Breadcrumb items={[{ label: "Hem", href: "/" },{ label: "UK ETA-information", href: "/eta-info/what-is-eta" },{ label: "Standard Visitor-visum" }]} /></div>
    </div>);
}
